[project]
name = "paceterminal-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "openai>=1.109.1",
    "python-dotenv>=1.1.1",
    "ruff>=0.13.2",
]
